config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)

  scope '(:locale)', locale: /fr|en/ do

  devise_for :users

  root to: 'pages#home'

  get 'about', to: 'pages#about'

  resources :contacts, only: [:new, :create]

  resources :articles, only: [:index]

  resources :restaurants do
    resources :reviews, only: [:create]
    resources :articles, only: [:show]
    collection do
      get 'mood',  to: "restaurants#mood"
      get 'amsterdam', to: "restaurants#amsterdam"
      get 'barcelone', to: "restaurants#barcelone"
      get 'berlin', to: "restaurants#berlin"
      get 'cap-ferret', to: "restaurants#cap_ferret"
      get 'hanoi', to: "restaurants#hanoi"
      get 'jerusalem', to: "restaurants#jerusalem"
      get 'lisbonne', to: "restaurants#lisbonne"
      get 'londres', to: "restaurants#londres"
      get 'los-angeles', to: "restaurants#los_angeles"
      get 'marrakech', to: "restaurants#marrakech"
      get 'miami', to: "restaurants#miami"
      get 'montreal', to: "restaurants#montreal"
      get 'new-york', to: "restaurants#new_york"
      get 'nouvelle-orleans', to: "restaurants#nouvelle_orleans"
      get 'paris', to: "restaurants#paris"
      get 'piana', to: "restaurants#piana"
      get 'tel-aviv', to: "restaurants#tel_aviv"
      get 'san-francisco', to: "restaurants#san_francisco"
      get 'hawaii', to: "restaurants#hawaii"
    end

    end

  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

  has_one :article
  has_many :reviews

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :name, presence: true
  validates :city, presence: true, inclusion: {in:["Amsterdam", "Barcelone", "Berlin", "Cap-ferret", "Hanoi", "Jérusalem", "Lisbonne", "Londres", "Los Angeles", "Marrakech", "Miami", "Montreal", "New-York", "Nouvelle-Orléans" "Paris", "Piana", "San Francisco", "Tel-aviv", "Hawaii Islands"]}
  validates :mood, inclusion: {in:["brunch", "lunch on the go", "business lunch", "tea time", "apero", "tapas", "trendy casual dinner", "classy dinner", "where to take my date for dinner?"]}
  validates :picture, presence:true

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def mood
    @restaurants = Restaurant.where(mood: params[:mood])
  end

  def amsterdam
    @restaurants = Restaurant.where(city: "Amsterdam")
  end

  def barcelone
    @restaurants = Restaurant.where(city: "Barcelone")
  end

  def berlin
    @restaurants = Restaurant.where(city: "Berlin")
  end

  def cap_ferret
    @restaurants = Restaurant.where(city: "Cap-ferret")
  end

  def hanoi
    @restaurants = Restaurant.where(city: "Hanoi")
  end

  def jerusalem
    @restaurants = Restaurant.where(city: "Jérusalem")
  end

  def lisbonne
    @restaurants = Restaurant.where(city: "Lisbonne")
  end

  def londres
    @restaurants = Restaurant.where(city: "Londres")
  end

  def los_angeles
    @restaurants = Restaurant.where(city: "Los Angeles")
  end

  def marrakech
    @restaurants = Restaurant.where(city: "Marrakech")
  end

  def montreal
    @restaurants = Restaurant.where(city: "Montreal")
  end

  def new_york
    @restaurants = Restaurant.where(city: "New-York")
  end

  def paris
    @restaurants = Restaurant.where(city: "Paris").paginate(:page => params[:page], :per_page => 9, total_entries: 19)
  end

  def piana
    @restaurants = Restaurant.where(city: "Piana")
  end

  def tel_aviv
    @restaurants = Restaurant.where(city: "Tel-aviv")
  end

  def san_francisco
    @restaurants = Restaurant.where(city: "San Francisco")
  end

   def miami
    @restaurants = Restaurant.where(city: "Miami")
  end

   def nouvelle_orleans
    @restaurants = Restaurant.where(city: "Nouvelle-Orléans")
  end

  def hawaii
    @restaurants = Restaurant.where(city: "Hawaii Islands")
  end

end

app/views/restaurants/amsterdam.html.erb
<div class="col-xs-12 col-md-8">
  <div class="row">
    <% @restaurants.each do |restaurant| %>
      <div class="col-xs-12 col-sm-6 col-lg-4">
        <div class="white-box">
          <%= link_to restaurant_article_path(restaurant.id, restaurant.article)  do %>
            <div class="container-pola">
              <%= image_tag restaurant.picture, id:"pola" %>
            </div>
          <% end %>
          <p class="restaurant"><%= restaurant.name %></p>
          <p class="city"><strong><%= restaurant.city %></strong></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/barcelone.html.erb
<div class="col-xs-12 col-md-8">
  <div class="row">
    <% @restaurants.each do |restaurant| %>
      <div class="col-xs-12 col-sm-6 col-lg-4">
        <div class="white-box">
          <%= link_to restaurant_article_path(restaurant.id, restaurant.article)  do %>
            <div class="container-pola">
              <%= image_tag restaurant.picture, id:"pola" %>
            </div>
          <% end %>
          <p class="restaurant"><%= restaurant.name %></p>
          <p class="city"><strong><%= restaurant.city %></strong></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/berlin.html.erb
<div class="col-xs-12 col-md-8">
  <div class="row">
    <% @restaurants.each do |restaurant| %>
      <div class="col-xs-12 col-sm-6 col-lg-4">
        <div class="white-box">
          <%= link_to restaurant_article_path(restaurant.id, restaurant.article)  do %>
            <div class="container-pola">
              <%= image_tag restaurant.picture, id:"pola" %>
            </div>
          <% end %>
          <p class="restaurant"><%= restaurant.name %></p>
          <p class="city"><strong><%= restaurant.city %></strong></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/cap_ferret.html.erb
<div class="col-xs-12 col-md-8">
  <div class="row">
    <% @restaurants.each do |restaurant| %>
      <div class="col-xs-12 col-sm-6 col-lg-4">
        <div class="white-box">
          <%= link_to restaurant_article_path(restaurant.id, restaurant.article)  do %>
            <div class="container-pola">
              <%= image_tag restaurant.picture, id:"pola" %>
            </div>
          <% end %>
          <p class="restaurant"><%= restaurant.name %></p>
          <p class="city"><strong><%= restaurant.city %></strong></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/hanoi.html.erb
<div class="col-xs-12 col-md-8">
  <div class="row">
    <% @restaurants.each do |restaurant| %>
      <div class="col-xs-12 col-sm-6 col-lg-4">
        <div class="white-box">
          <%= link_to restaurant_article_path(restaurant.id, restaurant.article)  do %>
            <div class="container-pola">
              <%= image_tag restaurant.picture, id:"pola" %>
            </div>
          <% end %>
          <p class="restaurant"><%= restaurant.name %></p>
          <p class="city"><strong><%= restaurant.city %></strong></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/hawaii.html.erb
<div class="col-xs-12 col-md-8">
  <div class="row">
    <% @restaurants.each do |restaurant| %>
      <div class="col-xs-12 col-sm-6 col-lg-4">
        <div class="white-box">
          <%= link_to restaurant_article_path(restaurant.id, restaurant.article)  do %>
            <div class="container-pola">
              <%= image_tag restaurant.picture, id:"pola" %>
            </div>
          <% end %>
          <p class="restaurant"><%= restaurant.name %></p>
          <p class="city"><strong><%= restaurant.city %></strong></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/jerusalem.html.erb
<div class="col-xs-12 col-md-8">
  <div class="row">
    <% @restaurants.each do |restaurant| %>
      <div class="col-xs-12 col-sm-6 col-lg-4">
        <div class="white-box">
          <%= link_to restaurant_article_path(restaurant.id, restaurant.article)  do %>
            <div class="container-pola">
              <%= image_tag restaurant.picture, id:"pola" %>
            </div>
          <% end %>
          <p class="restaurant"><%= restaurant.name %></p>
          <p class="city"><strong><%= restaurant.city %></strong></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/los_angeles.html.erb
<div class="col-xs-12 col-md-8">
  <div class="row">
    <% @restaurants.each do |restaurant| %>
      <div class="col-xs-12 col-sm-6 col-lg-4">
        <div class="white-box">
          <%= link_to restaurant_article_path(restaurant.id, restaurant.article)  do %>
            <div class="container-pola">
              <%= image_tag restaurant.picture, id:"pola" %>
            </div>
          <% end %>
          <p class="restaurant"><%= restaurant.name %></p>
          <p class="city"><strong><%= restaurant.city %></strong></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/marrakech.html.erb
<div class="col-xs-12 col-md-8">
  <div class="row">
    <% @restaurants.each do |restaurant| %>
      <div class="col-xs-12 col-sm-6 col-lg-4">
        <div class="white-box">
          <%= link_to restaurant_article_path(restaurant.id, restaurant.article)  do %>
            <div class="container-pola">
              <%= image_tag restaurant.picture, id:"pola" %>
            </div>
          <% end %>
          <p class="restaurant"><%= restaurant.name %></p>
          <p class="city"><strong><%= restaurant.city %></strong></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/montreal.html.erb
<div class="col-xs-12 col-md-8">
  <div class="row">
    <% @restaurants.each do |restaurant| %>
      <div class="col-xs-12 col-sm-6 col-lg-4">
        <div class="white-box">
          <%= link_to restaurant_article_path(restaurant.id, restaurant.article)  do %>
            <div class="container-pola">
              <%= image_tag restaurant.picture, id:"pola" %>
            </div>
          <% end %>
          <p class="restaurant"><%= restaurant.name %></p>
          <p class="city"><strong><%= restaurant.city %></strong></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/new_york.html.erb
<div class="col-xs-12 col-md-8">
  <div class="row">
    <% @restaurants.each do |restaurant| %>
      <div class="col-xs-12 col-sm-6 col-lg-4">
        <div class="white-box">
          <%= link_to restaurant_article_path(restaurant.id, restaurant.article)  do %>
            <div class="container-pola">
              <%= image_tag restaurant.picture, id:"pola" %>
            </div>
          <% end %>
          <p class="restaurant"><%= restaurant.name %></p>
          <p class="city"><strong><%= restaurant.city %></strong></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/nouvelle_orleans.html.erb
<div class="col-xs-12 col-md-8">
  <div class="row">
    <% @restaurants.each do |restaurant| %>
      <div class="col-xs-12 col-sm-6 col-lg-4">
        <div class="white-box">
          <%= link_to restaurant_article_path(restaurant.id, restaurant.article)  do %>
            <div class="container-pola">
              <%= image_tag restaurant.picture, id:"pola" %>
            </div>
          <% end %>
          <p class="restaurant"><%= restaurant.name %></p>
          <p class="city"><strong><%= restaurant.city %></strong></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/paris.html.erb
<div class="col-xs-12 col-md-8">
  <div class="row">
    <% @restaurants.each do |restaurant| %>
      <div class="col-xs-12 col-sm-6 col-lg-4">
        <div class="white-box">
          <%= link_to restaurant_article_path(restaurant.id, restaurant.article)  do %>
            <div class="container-pola">
              <%= image_tag restaurant.picture, id:"pola" %>
            </div>
          <% end %>
          <p class="restaurant"><%= restaurant.name %></p>
          <p class="city"><strong><%= restaurant.city %></strong></p>
        </div>
      </div>
    <% end %>
    <%= will_paginate @restaurants, :previous_label => "<<", :next_label => ">>" %>
  </div>
</div>

app/views/restaurants/tel_aviv.html.erb
<div class="col-xs-12 col-md-8">
  <div class="row">
    <% @restaurants.each do |restaurant| %>
      <div class="col-xs-12 col-sm-6 col-lg-4">
        <div class="white-box">
          <%= link_to restaurant_article_path(restaurant.id, restaurant.article)  do %>
            <div class="container-pola">
              <%= image_tag restaurant.picture, id:"pola" %>
            </div>
          <% end %>
          <p class="restaurant"><%= restaurant.name %></p>
          <p class="city"><strong><%= restaurant.city %></strong></p>
        </div>
      </div>
    <% end %>
  </div>
</div>