config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)

  scope '(:locale)', locale: /fr|en/ do

  devise_for :users

  root to: 'pages#home'

  get 'about', to: 'pages#about'

  resources :contacts, only: [:new, :create]

  resources :articles, only: [:index]

  resources :restaurants do
    resources :reviews, only: [:create]
    resources :articles, only: [:show]
    collection do
      get 'mood',  to: "restaurants#mood"
      get 'amsterdam', to: "restaurants#amsterdam"
      get 'barcelone', to: "restaurants#barcelone"
      get 'berlin', to: "restaurants#berlin"
      get 'cap-ferret', to: "restaurants#cap_ferret"
      get 'hanoi', to: "restaurants#hanoi"
      get 'jerusalem', to: "restaurants#jerusalem"
      get 'lisbonne', to: "restaurants#lisbonne"
      get 'londres', to: "restaurants#londres"
      get 'los-angeles', to: "restaurants#los_angeles"
      get 'marrakech', to: "restaurants#marrakech"
      get 'miami', to: "restaurants#miami"
      get 'montreal', to: "restaurants#montreal"
      get 'new-york', to: "restaurants#new_york"
      get 'nouvelle-orleans', to: "restaurants#nouvelle_orleans"
      get 'paris', to: "restaurants#paris"
      get 'piana', to: "restaurants#piana"
      get 'tel-aviv', to: "restaurants#tel_aviv"
      get 'san-francisco', to: "restaurants#san_francisco"
      get 'hawaii', to: "restaurants#hawaii"
    end

    end

  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Food Globeuses</title>

  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= csrf_meta_tags %>

</head>

<body>

  <%= render "shared/flashes" %>

  <% if current_page?('/users/sign_in') == false && current_page?('/users/password/new') == false %>

    <header>
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
        <nav class="navbar-default">
          <div class="logo">
            <a href="#">
              <%= image_tag "logo.png", class: "img-responsive img-center"%>
            </a>
          </div>
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-right">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
            <ul class="nav navbar-nav navbar-left">
              <li role="presentation" class="translation">
                <ul>
                  <%= link_to "EN", url_for( :locale => 'en' ) %>
                  /
                  <%= link_to "FR", url_for( :locale => 'fr' ) %>
                </ul>
              </li>
                <li role="presentation" class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">Destinations<span class="caret"></span>
                </a>
                  <ul class="dropdown-menu" role="menu">
                    <li><%= link_to "Amsterdam", amsterdam_restaurants_path %></li>
                    <li><%= link_to "Barcelone", barcelone_restaurants_path %></li>
                    <li><%= link_to "Berlin", berlin_restaurants_path %></li>
                    <li><%= link_to "Cap-Ferret", cap_ferret_restaurants_path %></li>
                    <li><%= link_to "Hanoi", hanoi_restaurants_path %></li>
                    <li><%= link_to "Jérusalem", jerusalem_restaurants_path %></li>
                    <li><%= link_to "Hawaii Islands", hawaii_restaurants_path %></li>
                    <li><%= link_to "Lisbonne", lisbonne_restaurants_path %></li>
                    <li><%= link_to "Londres", londres_restaurants_path %></li>
                    <li><%= link_to "Los Angeles", los_angeles_restaurants_path %></li>
                    <li><%= link_to "Marrakech", marrakech_restaurants_path %></li>
                    <li><%= link_to "Miami", miami_restaurants_path %></li>
                    <li><%= link_to "Montreal", montreal_restaurants_path %></li>
                    <li><%= link_to "New-York", new_york_restaurants_path %></li>
                    <li><%= link_to "Nouvelle-Orléans", nouvelle_orleans_restaurants_path %></li>
                    <li><%= link_to "Paris", paris_restaurants_path %></li>
                    <li><%= link_to "Piana", piana_restaurants_path %></li>
                    <li><%= link_to "San Francisco", san_francisco_restaurants_path %></li>
                    <li><%= link_to "Tel-aviv", tel_aviv_restaurants_path %></li>
                  </ul>
              </li>
              <li role="presentation" class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">Mood<span class="caret"></span>
                </a>
                  <ul class="dropdown-menu" role="menu">
                    <li><%= link_to "Brunch", mood_restaurants_path(:mood => "brunch") %></li>
                    <li><%= link_to "Lunch on the go", mood_restaurants_path(:mood => "lunch on the go") %></li>
                    <li><%= link_to "Business lunch", mood_restaurants_path(:mood => "business lunch") %></li>
                    <li><%= link_to "Tea time", mood_restaurants_path(:mood => "tea time") %></li>
                    <li><%= link_to "Apero", mood_restaurants_path(:mood => "apero") %></li>
                    <li><%= link_to "Tapas", mood_restaurants_path(:mood => "tapas") %></li>
                    <li><%= link_to "Trendy casual dinner", mood_restaurants_path(:mood => "trendy casual dinner") %></li>
                    <li><%= link_to "Classy dinner", mood_restaurants_path(:mood => "classy dinner") %></li>
                    <li><%= link_to "Where to take my date for dinner?", mood_restaurants_path(:mood => "where to take my date for dinner?") %></li>
                  </ul>
              </li>
            </ul>
              <div class="collapse navbar-collapse" id="navbar-right">
                <ul class="nav navbar-nav navbar-right">
                  <li><%= link_to "Home", root_path %></li>
                  <li><%= link_to "About", about_path %></li>
                  <li><%= link_to "Contact", new_contact_path %></li>
                  <li><a href="#social"><%= t('.followus') %></a></li>
                </ul>
              </div>
          </div>
        </nav>
        </div>
        </div>
        </div>
      </header>

<div class="container padding-top">
  <div class="row">


  <%= yield %>

  <div class="col-xs-12 col-md-3 col-md-offset-1">
    <div class="side-bar">
      <h4 class="widget-title"><%= t('.about') %></h4>
      <%= image_tag "about.jpg", class: "img-about" %>
      <p>
        <%= t('.presentation') %>
      </p>
      <%= link_to t('.learnmore'), about_path, class: "link" %>
      <h4 class="widget-title" id="social"><%= t('.followus') %></h4>
      <div class="row">
        <ul class="list-inline social-sidebar">
          <li>
            <a href="https://www.facebook.com/foodglobeuses" target="_blank">
              <%= image_tag "facebook-2.png", class: "social-sidebar-img"%>
            </a>
          </li>
          <li>
            <a href="https://twitter.com" target="_blank">
              <%= image_tag "twitter-2.png", class: "social-sidebar-img"%>
            </a>
          </li>
          <li>
            <a href="http://www.pinterest.com" target="_blank">
              <%= image_tag "pinterest-2.png", class: "social-sidebar-img"%>
            </a>
          </li>
          <li>
            <a href="https://instagram.com/foodglobeuses/" target="_blank">
              <%= image_tag "instagram-2.png", class: "social-sidebar-img"%>
            </a>
          </li>
        </ul>
      </div>
      <h4 class="widget-title"><%= t('.search') %></h4>
      <div id="search">
      <%= form_tag(articles_path, method: :get, class: "form-inline") do %>
        <div class="wrapper">
          <input type="text" name="search">
          <button><i class="fa fa-search"></i></button>
        </div>
      <% end %>
      </div>
      <h4 class="widget-title">Instagram</h4>
      <ul class="list-inline instagram">
        <li>
          <a href="https://instagram.com/p/2J1ZPEDr_i/?taken-by=foodglobeuses" target="_blank">
            <%= image_tag "crab_cakes.png", class: "img-instagram"%>
          </a>
        </li>
        <li>
          <a href="https://instagram.com/p/1nv7tBDr9H/?taken-by=foodglobeuses" target="_blank">
            <%= image_tag "coffee.png", class: "img-instagram"%>
          </a>
        </li>
        <li>
          <a href="https://instagram.com/p/zh0K1fjr3a/?taken-by=foodglobeuses" target="_blank">
            <%= image_tag "salad.png", class: "img-instagram"%>
          </a>
        </li>
        <li>
          <a href="https://instagram.com/p/0sTEmgjr-j/?taken-by=foodglobeuses" target="_blank">
            <%= image_tag "muesli.png", class: "img-instagram"%>
          </a>
        </li>
        <li>
          <a href="https://instagram.com/p/2Hfs_vDr6X/?taken-by=foodglobeuses" target="_blank">
            <%= image_tag "pancakes.png", class: "img-instagram"%>
          </a>
        </li>
        <li>
          <a href="https://instagram.com/p/z5PuqFjr7K/?taken-by=foodglobeuses" target="_blank">
            <%= image_tag "tataki.png", class: "img-instagram"%>
          </a>
        </li>
        <li>
          <a href="https://instagram.com/p/tIoQCQjrwQ/?taken-by=foodglobeuses" target="_blank">
            <%= image_tag "tuna.png", class: "img-instagram"%>
          </a>
        </li>
        <li>
          <a href="https://instagram.com/p/o8zLekDr-J/?taken-by=foodglobeuses" target="_blank">
            <%= image_tag "frozen.png", class: "img-instagram"%>
          </a>
        </li>
        <li>
          <a href="https://instagram.com/p/ortdacjrxf/?taken-by=foodglobeuses" target="_blank">
            <%= image_tag "eggplant.png", class: "img-instagram"%>
          </a>
        </li>
      </ul>
    </div>
  </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col xs-12">
      <div id="footer-social">
          <p>© 2015 foodglobeuses.com ALL RIGHTS RESERVED.</p>
          <div class="sclicon">
            <a href="https://www.facebook.com/foodglobeuses" target="_blank">
              <%= image_tag "facebook.png", id:"img-size-footer"%>
            </a>
            <a href="https://twitter.com" target="_blank">
              <%= image_tag "twitter.png", id:"img-size-footer"%>
            </a>
            <a href="http://www.pinterest.com" target="_blank">
              <%= image_tag "pinterest.png", id:"img-size-footer"%>
            </a>
            <a href="https://instagram.com/foodglobeuses/" target="_blank">
              <%= image_tag "instagram.png", id:"img-size-footer"%>
            </a>
          </div>
      </div>
    </div>
  </div>
</div>

<% else %>
  <%= yield %>
<% end %>

  <%= javascript_include_tag "https://maps.google.com/maps/api/js?sensor=false" %>
  <%= javascript_include_tag "https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" %>
  <%= javascript_include_tag 'application'%>
  <%= yield(:after_js) %>

  </body>
</html>